# დავალება 1


cars = ["bmw","mersedes","honda","toyota","opel","bugatti","fiat","subaru","ferarri","dodji"]



print(cars[0:5])


print(cars[7:10])

print(cars[3:8])



# დავალება 2


names = ["gega","giorgi","lasha","gvanca","rezi","dachi","nugzari","alexsi","irakli","ilia","shota","zuka","zura","goga","giga"]


print(names[-16:-13])


print(names[-11:])

print(names[-9:-1])



# დავალება 3


airplane = "თვითფრინავი"


print(airplane[7:])


# დავალება 4


word = "Programer"


print(word[0:3])

print(word[-9:-6])


# დავალება 5


kviris_dgeebi = ["orsabati","samsabati","otxsabati","xutsabati","paraskevi","sabati","kvira"]



print(kviris_dgeebi[0:5])

print(kviris_dgeebi[-7:-2])

print(kviris_dgeebi[5:])

print(kviris_dgeebi[-2:])



# დავალება 6


word_2 = "Python slicing is very powerful"


print(word_2[0:6])

print(word_2[6:14])

print(word_2[-8:])
